site_name: Joey's Knowledge Base
site_url: https://Joey060403.github.io/my-notes/

theme:
  name: material
  language: zh
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: 切换到深色模式
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: 切换到浅色模式
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - toc:
      permalink: true

extra_javascript:
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - PMPP:
      - Overview: PMPP/index.md
      - "Ch02 · Heterogeneous Data Parallel Computing": PMPP/ch2.md
      - "Ch03 · Multidimensional Grids and Data": PMPP/ch3.md
      - "Ch04 · Compute Architecture and Scheduling": PMPP/ch4.md
      - "Ch05 · Memory Architecture and Data Locality": PMPP/ch5.md
      - "Ch06 · Performance Considerations": PMPP/ch6.md
  - Deep Learning:
      - Test: dl/test.md